language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 
install:
 - sudo apt-get install python-dev xvfb x11-utils x11-apps
 - sudo apt-get install binutils-avr gcc-avr scons arduino
 - pip install -r requirements-test.txt
 - pip install .
 - pip install coveralls

script:  
 - cd tests 
 - ls -la /usr/bin/python*
 - python --version
 - python2 --version
 - python3 --version
 - which python
 - env
 - head /usr/bin/scons
 - scons
 - sudo sed -i -e "s+/usr/bin/python+/usr/bin/python2+" 		/usr/bin/scons
 - head /usr/bin/scons
 - scons
 - nosetests -v --with-coverage --cover-package=pyavrutils  .
  
after_success:
 - coveralls
