language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 
install:
 - sudo apt-get install python-dev xvfb x11-utils x11-apps
 - sudo apt-get install binutils-avr gcc-avr avr-libc scons arduino
 - pip install -r requirements-test.txt
 - pip install .
 - pip install coveralls

# scons is Python2 only!

script:  
 - cd tests 
 - sudo sed -i -e "s/python/python2/" 		/usr/bin/scons
 - nosetests -v --with-coverage --cover-package=pyavrutils  .
  
after_success:
 - coveralls
